---
title: "Script to create additional tables/materials"
author: "Christian Holland"
date: "6/23/2019"
output: html_document
---

```{r "knitr config", cache=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::knit(..., quiet = TRUE)
```
### Libraries and sources
These libraries and sources are used in this analysis 
```{r "setup", message=F}
library(tidyverse)
library(tidylog)

options("tidylog.display" = list(print))
```
### Genereal robustness

### In silico benchmark
#### Accession ids of bulk tf perturbation experiments
```{r}
sample_anno = raw_anno = read_delim("data/in_silico_benchmark/meta_data/sample_annotations.csv", delim = ";")

tf_pert = readRDS("output/in_silico_benchmark/meta_data/meta_df.rds") %>%
  filter(class == "single_tf_perturbation") %>%
  select(id, description, target, perturbation, molecule, accession) %>%
  inner_join(sample_anno, by="id")

write_csv(tf_pert, 
          "paper/auxiliary_files/MatS1_tf_perturbation_experiments.csv")
write_csv(tf_pert, 
          "~/Google Drive/Paper/scRNA_benchmark/ReconsiderGenBio/AdditionalFiles/MatS1_tf_perturbation_experiments.csv")
```

#### Accession ids of bulk tf perturbation experiments
```{r}
sample_anno = raw_anno = read_delim("data/in_silico_benchmark/meta_data/sample_annotations.csv", delim = ";")

pw_pert = readRDS("output/in_silico_benchmark/meta_data/meta_df.rds") %>%
  filter(class == "single_pw_perturbation") %>%
  select(id, target, perturbation, molecule, accession) %>%
  inner_join(sample_anno, by="id")

write_csv(pw_pert, 
          "paper/auxiliary_files/MatS2_pathway_perturbation_experiments.csv")
write_csv(pw_pert, 
          "~/Google Drive/Paper/scRNA_benchmark/ReconsiderGenBio/AdditionalFiles/MatS2_pathway_perturbation_experiments.csv")
```
