---
title: "Arrange individual figures into a collage"
author: "Christian Holland"
date: "6/23/2019"
output: html_document
---

```{r "knitr config", cache=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::knit(..., quiet = TRUE)
```
### Libraries and sources
These libraries and sources are used in this analysis 
```{r "setup", message=F}
library(tidyverse)
library(cowplot)
library(gridExtra)
library(ggpubr)
library(ggrepel)
library(ggplotify)
library(grid)
library(magick)
library(tidylog)

options("tidylog.display" = list(print))
theme_set(theme_cowplot())
```
### General robustness
#### Main
```{r}
progeny_path = "fig/general_robustness/progeny/"
dorothea_path = "fig/general_robustness/dorothea/"
gogsea_path = "fig/general_robustness/gogsea/"
p_gene_coverage_vs_auroc = readRDS(str_c(progeny_path, "gene_cov_vs_auroc_all_footprints.rds")) +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        legend.title = element_text(size=12),
        legend.text = element_text(size=12),
        legend.position = c(0.05,0.10)) +
  ylim(0.45,0.75)
d_gene_coverage_vs_auroc = readRDS(str_c(dorothea_path, "gene_cov_vs_auroc.rds")) +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  ylim(0.45,0.75)
g_gene_coverage_vs_auroc = readRDS(str_c(gogsea_path, "gene_cov_vs_auroc.rds")) +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  ylim(0.45,0.75)


general_robustness_main = plot_grid(
  d_gene_coverage_vs_auroc, p_gene_coverage_vs_auroc, g_gene_coverage_vs_auroc,
  ncol=3, labels=c("a", "b", "c"), label_size = 18,
  align = "vh", axis = "btlr"
)
ggsave("paper/figures/main_general_robustness.png", 
       general_robustness_main,
       width = 10, height = 5)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/Figure1.png",
       general_robustness_main,
       width=10, height=5)
```

#### Supp1
```{r}
progeny_path = "fig/general_robustness/progeny/"
dorothea_path = "fig/general_robustness/dorothea/"
gogsea_path = "fig/general_robustness/gogsea/"



workflow = ggdraw() +
  draw_image("fig/general_robustness/workflow_with_gogsea.jpg") 
d_auroc_vs_auprc = readRDS(str_c(dorothea_path, "auroc_vs_auprc.rds"))
p_auroc_vs_auprc = readRDS(str_c(progeny_path, "auroc_vs_auprc.rds"))
g_auroc_vs_auprc = readRDS(str_c(gogsea_path, "auroc_vs_auprc.rds"))
mapping_table = readRDS("fig/general_robustness/gogsea/progeny_go_mapping.rds")

top = plot_grid(workflow, labels=c("a"), label_size = 18)
bottom = plot_grid(mapping_table, labels = c("d"), label_size = 18)
mid = plot_grid(
  d_auroc_vs_auprc, p_auroc_vs_auprc, g_auroc_vs_auprc, labels = c("b", "c", "e"), label_size = 18, ncol=3
)
general_robustness_supp1 = plot_grid(top, mid, bottom, ncol=1)

ggsave("paper/figures/supp_general_robustness_1.png", 
       general_robustness_supp1,
       width = 12, height = 12)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure1.png",
       general_robustness_supp1,
       width=12, height=12)
```
#### Supp2
```{r}
progeny_path = "fig/general_robustness/progeny/"
gogsea_path = "fig/general_robustness/gogsea/"

p_gene_coverage_vs_auroc = readRDS(str_c(progeny_path, "pw_gene_cov_vs_auroc_all_footprints.rds")) +
  ylim(0,1)

g_gene_coverage_vs_auroc = readRDS(str_c(gogsea_path, "gene_cov_vs_auroc_pw.rds")) +
  ylim(0,1)

p_auroc_vs_auprc = readRDS(str_c(progeny_path, "pw_auroc_vs_auprc.rds"))
g_auroc_vs_auprc = readRDS(str_c(gogsea_path, "auroc_vs_auprc_pw.rds"))


# general_robustness_supp2 = plot_grid(
#   p_gene_coverage_vs_auroc, g_gene_coverage_vs_auroc, 
#   p_auroc_vs_auprc, g_auroc_vs_auprc, labels = c("a", "c", "b", "d"), 
#   label_size = 18, align = "hv", axis = "lt")

general_robustness_supp2 = plot_grid(
  p_gene_coverage_vs_auroc, g_gene_coverage_vs_auroc, 
  labels = c("a", "b"), ncol=1, 
  label_size = 18, align = "hv", axis = "lt")

ggsave("paper/figures/supp_general_robustness_2.pdf", 
       general_robustness_supp2,
       width = 15, height = 20)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure2.png",
       general_robustness_supp2,
       width=15, height=20)
```


### In silico benchmark
#### Main
```{r "in silico benchmark - main"}
dorothea_path = "fig/in_silico_benchmark/dorothea/"
metaviper_path = "fig/in_silico_benchmark/metaviper/"
daucell_path = "fig/in_silico_benchmark/daucell/"
progeny_path = "fig/in_silico_benchmark/progeny/"
paucell_path = "fig/in_silico_benchmark/paucell/"

sim_workflow = ggdraw() +
  draw_image("fig/in_silico_benchmark/simulation_workflow.jpg")

d_roc_curve = readRDS(str_c(dorothea_path, "roc_curve.rds")) + labs(title = "1. Step") + theme(plot.title = element_text(hjust = 0.5))
d_auroc_vs_cov = readRDS(str_c(dorothea_path, "auroc_vs_cov.rds")) + labs(title = "2. Step") + theme(plot.title = element_text(hjust = 0.5))
d_auroc_dist_hmap = readRDS(str_c(dorothea_path, "auroc_distance_hmap.rds")) + labs(title = "3. Step") + theme(plot.title = element_text(hjust = 0.5))

mv_auroc_vs_cov = readRDS(str_c(metaviper_path, "auroc_vs_cov.rds"))
dauc_auroc_vs_cov = readRDS(str_c(daucell_path, "auroc_vs_cov.rds"))
p_auroc_vs_footprints = readRDS(str_c(progeny_path, "auroc_vs_footprints.rds"))
pauc_auroc_vs_footprints = readRDS(str_c(paucell_path, "auroc_vs_footprints.rds"))

aligned_plots = align_plots(d_roc_curve + theme(legend.position = c(0.65,0.1)),
                            dauc_auroc_vs_cov + theme(legend.position = "none"),
                            align = "hv", axis = "btlr")

top = plot_grid(
  sim_workflow, labels = c("a"), label_size = 18
)

mid = plot_grid(
  aligned_plots[[1]],
  d_auroc_vs_cov + theme(legend.position = "none"), 
  d_auroc_dist_hmap,
  ncol=3, labels = c("b"), label_size = 18, align="h", axis = "bt"
  )

bottom = plot_grid(
  aligned_plots[[2]],
  mv_auroc_vs_cov + theme(legend.position = "none"),
  p_auroc_vs_footprints + theme(legend.position = "none"),
  pauc_auroc_vs_footprints + theme(legend.position = "none"),
  ncol=4, labels=c("c", "d", "e", "f"), label_size = 18
  )

in_silico_benchmark_main = plot_grid(
  top, mid, bottom,
  ncol=1, rel_heights = c(1.1,1,1)
  )

ggsave("paper/figures/main_in_silico_benchmark.png", 
       in_silico_benchmark_main,
       width = 15, height = 15)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/Figure2.png",
       in_silico_benchmark_main,
       width=15, height=15)
```

#### Supp1
```{r}
dorothea_path = "fig/in_silico_benchmark/dorothea/"
progeny_path = "fig/in_silico_benchmark/progeny/"


d_benchmark_data = readRDS(str_c(dorothea_path, "benchmark_data.rds")) + 
  theme(legend.title = element_text(), 
        legend.position = c(0.01,0.8)) + 
  labs(fill = "Confidence level",
       title = "TF perturbation experiments")
p_benchmark_data = readRDS(str_c(progeny_path, "benchmark_data.rds")) + 
  labs(title = "Pathway perturbation experiments")

in_silico_benchmark_supp_1 = plot_grid(
  d_benchmark_data, p_benchmark_data, 
  labels = c("a", "b"), label_size = 18, align = "h", axis="tb"
  )

ggsave("paper/figures/supp_in_silico_benchmark_1.pdf", 
       in_silico_benchmark_supp_1,
       width = 10, height = 5)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure3.png",
       in_silico_benchmark_supp_1,
       width=10, height=5)


```


#### Supp2
```{r "in silico benchmark 2 - supp"}
r_c_d = readRDS("fig/in_silico_benchmark/real_count_distribution.rds")
s_c_d = readRDS("fig/in_silico_benchmark/sim_count_distribution.rds")

r_m_vs_v = readRDS("fig/in_silico_benchmark/real_mean_vs_var.rds")
s_m_vs_v = readRDS("fig/in_silico_benchmark/sim_mean_vs_var.rds")

l_real = readRDS("fig/in_silico_benchmark/real_lib_vs_cov.rds")
l_sim =  readRDS("fig/in_silico_benchmark/sim_lib_vs_cov.rds")

in_silico_benchmark_supp_2 = plot_grid(
  r_c_d + labs(title = "Real single cell"), 
  s_c_d + labs(title = "Simulated single cell"),
  r_m_vs_v,
  s_m_vs_v,
  l_real, 
  l_sim,
  align = "vh", axis = "lrbt", labels = c("a", "", "b", "", "c", ""), 
  label_size = 18, ncol=2
)

ggsave("paper/figures/supp_in_silico_benchmark_2.png", 
       in_silico_benchmark_supp_2,
       width = 10, height = 15)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure4.png",
       in_silico_benchmark_supp_2,
       width=10, height=15)
```

#### Supp3
```{r "in silico benchmark 3 - supp"}
dorothea_path = "fig/in_silico_benchmark/dorothea/"
metaviper_path = "fig/in_silico_benchmark/metaviper/"
daucell_path = "fig/in_silico_benchmark/daucell/"
progeny_path = "fig/in_silico_benchmark/progeny/"
paucell_path = "fig/in_silico_benchmark/paucell/"


d_variance_hmap = readRDS(str_c(dorothea_path, "variance_hmap.rds"))
mv_variance_hmap = readRDS(str_c(metaviper_path, "variance_hmap.rds"))
dauc_variance_hmap = readRDS(str_c(daucell_path, "variance_hmap.rds"))
progeny_variance_hmap = readRDS(str_c(progeny_path, "variance_hmap.rds"))
pauc_variance_hmap = readRDS(str_c(paucell_path, "variance_hmap.rds"))

in_silico_benchmark_supp_3 = plot_grid(
  d_variance_hmap,
  dauc_variance_hmap,
  mv_variance_hmap,
  progeny_variance_hmap,
  pauc_variance_hmap,
  labels = c("a", "b", "c", "d", "e"), label_size = 18,
  ncol = 3
  )

ggsave("paper/figures/supp_in_silico_benchmark_3.png", 
       in_silico_benchmark_supp_3,
       width = 15, height = 10)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure5.png",
       in_silico_benchmark_supp_3,
       width=15, height=10)
```
#### Supp4
```{r "in silico benchmark 4 - supp"}
dorothea_path = "fig/in_silico_benchmark/dorothea/"
metaviper_path = "fig/in_silico_benchmark/metaviper/"
daucell_path = "fig/in_silico_benchmark/daucell/"
progeny_path = "fig/in_silico_benchmark/progeny/"
paucell_path = "fig/in_silico_benchmark/paucell/"

d_auroc_vs_auprc = readRDS(str_c(dorothea_path, "auroc_vs_auprc.rds"))
mv_auroc_vs_auprc = readRDS(str_c(metaviper_path, "auroc_vs_auprc.rds")) + theme(legend.position = "none")
dauc_auroc_vs_auprc = readRDS(str_c(daucell_path, "auroc_vs_auprc.rds")) + theme(legend.position = "none")
progeny_auroc_vs_auprc = readRDS(str_c(progeny_path, "auroc_vs_auprc.rds")) + theme(legend.position = "none")
pauc_auroc_vs_auprc = readRDS(str_c(paucell_path, "auroc_vs_auprc.rds")) + theme(legend.position = "none")


in_silico_benchmark_supp_4 = plot_grid(
  d_auroc_vs_auprc,
  dauc_auroc_vs_auprc,
  mv_auroc_vs_auprc,
  progeny_auroc_vs_auprc,
  pauc_auroc_vs_auprc,
  ncol = 3, labels = c("a", "b", "c", "d", "e"), label_size = 18, align = "hv", axis = "tblr"
  )

ggsave("paper/figures/supp_in_silico_benchmark_4.png", 
       in_silico_benchmark_supp_4,
       width = 15, height = 10)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure6.png",
       in_silico_benchmark_supp_4,
       width=15, height=10)
```

#### Supp5
```{r "in silico benchmark 5 - supp"}
dorothea_path = "fig/in_silico_benchmark/dorothea/"
metaviper_path = "fig/in_silico_benchmark/metaviper/"
daucell_path = "fig/in_silico_benchmark/daucell/"
progeny_path = "fig/in_silico_benchmark/progeny/"
paucell_path = "fig/in_silico_benchmark/paucell/"

d_hmap = readRDS(str_c(dorothea_path, "auroc_distance_hmap.rds")) + labs(title = "DoRothEA")
mv_hmap = readRDS(str_c(metaviper_path, "auroc_distance_hmap.rds"))
dauc_hmap = readRDS(str_c(daucell_path, "auroc_distance_hmap.rds"))
progeny_hmap = readRDS(str_c(progeny_path, "auroc_distance_hmap.rds"))
pauc_hmap = readRDS(str_c(paucell_path, "auroc_distance_hmap.rds"))


in_silico_benchmark_supp_5 = plot_grid(
  d_hmap,
  dauc_hmap,
  mv_hmap,
  progeny_hmap,
  pauc_hmap,
  ncol = 3, labels = c("a", "b", "c", "d", "e"), label_size = 18, align = "hv", axis = "tblr"
  )

ggsave("paper/figures/supp_in_silico_benchmark_5.png", 
       in_silico_benchmark_supp_5,
       width = 15, height = 10)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure7.png",
       in_silico_benchmark_supp_5,
       width=15, height=10)
```

### In vitro benchmark
#### Main
```{r "in vitro benchmark"}
path = "fig/in_vitro_benchmark/"

roc_vs_cov_ind = readRDS(str_c(path, "roc_vs_cov_ind.rds")) +
  theme(legend.position = "none",
        strip.background = element_blank(),
        strip.text.x = element_blank()) + 
  labs(y = "TF coverage")
roc_vs_cov_ind_sub = readRDS(str_c(path, "roc_vs_cov_ind_sub.rds")) + 
  labs(y="TF coverage", x=NULL)  


in_vitro_benchmark_main = plot_grid(
  roc_vs_cov_ind_sub, roc_vs_cov_ind, 
  ncol = 1, label_size = 18, labels = c("a", "b"),
  align = "v", axis="lr", rel_heights = c(0.5,1)
  )
ggsave("paper/figures/main_in_vitro_benchmark.png", 
       in_vitro_benchmark_main , width = 10, height=6.5)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/Figure3.png",
       in_vitro_benchmark_main,
       width=10, height=6.5)
```
#### Supp 1
```{r}
path = "fig/in_vitro_benchmark/"
h = readRDS(str_c(path, "histogram_of_logfc.rds"))
l = readRDS(str_c(path, "libsize_num_cells.rds"))
q = readRDS(str_c(path, "quality_check.rds"))
b = readRDS(str_c(path, "benchmark_data.rds")) + 
  theme(legend.title = element_text()) +
  labs(fill = "Confidence level")

roc_vs_pr_ind = readRDS(str_c(path, "roc_vs_pr_ind.rds")) + 
  theme(legend.position = "top")

col1 = align_plots(b, q, roc_vs_pr_ind, align = "v", axis = "l")



top = plot_grid(
  col1[[1]], l,
  ncol=2, labels = c("a", "b"), label_size = 18, align="h", axis="bt"
)

middle = plot_grid(
  col1[[2]], h,
  ncol=2, labels = c("c", "d"), label_size = 18, align="h", axis="bt",
  rel_widths = c(1,1.4)
)

bottom = plot_grid(
  col1[[3]], labels = c("e"), label_size = 18
)

in_vitro_benchmark_supp = plot_grid(top, middle, bottom, ncol=1, align="v", axis="l", rel_heights = c(1,1,1))

ggsave("paper/figures/supp_in_vitro_benchmark_1.png", 
       in_vitro_benchmark_supp , width = 14, height=14)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure8.png",
       in_vitro_benchmark_supp,
       width=14, height=14)
```

### Clustering analysis
#### Main1
```{r "clustering analysis"}
path = "fig/clustering_analysis/"

dend = readRDS(str_c(path, "dendogram.rds")) +
  theme(axis.text.x = element_text(angle = 0, size=10),
        plot.margin = unit(c(0.5,3.5,1,3.5), "cm"))
tf_boxplot = readRDS(str_c(path, "tf_boxplot.rds")) +
  theme(plot.margin = unit(c(0,2,0.5,0), "cm"))
pw_boxplot = readRDS(str_c(path, "pathway_boxplot.rds")) +
  theme(plot.margin = unit(c(0.5,2,0,0), "cm"))
viper_hmap = readRDS(str_c(path, "viper_hmap.rds"))
activity_vs_expression = readRDS(str_c(path, "activity_greater_expression.rds")) + guides(color = guide_legend(nrow=1)) +
  theme(plot.margin = unit(c(0.5,2,0,0), "cm"))

top = plot_grid(dend, labels = c("a"), label_size = 18)

left = plot_grid(tf_boxplot, activity_vs_expression, pw_boxplot, ncol = 1, 
                 labels = c("b", "c", "d"), 
                 align = "v", axis = "l",
                 label_size = 18)
right = plot_grid(viper_hmap, labels = c("e"), label_size = 18)

bottom = plot_grid(left, right, ncol=2, rel_widths = c(1,0.8))

clustering_analysis_main = plot_grid(top, bottom, ncol=1, rel_heights = c(0.25,1))

ggsave("paper/figures/main_clustering_analysis.png", 
       clustering_analysis_main,
       width = 15, height = 15)


ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/Figure4.png",
       clustering_analysis_main,
       width=15, height=15)

```


#### Supp1
```{r}
path = "fig/clustering_analysis/"

pdf(str_c(path, "common_regulons.pdf"), width=15, height=12)
readRDS(str_c(path, "common_regulons.rds"))
dev.off()

pdf(str_c(path, "common_scenic_regulons.pdf"), width=15, height = 12)
readRDS(str_c(path, "common_scenic_regulons.rds"))
dev.off()

common_regulons = ggdraw() +
  draw_image(str_c(path, "common_regulons.pdf"))

common_scenic_regulons = ggdraw() +
  draw_image(str_c(path, "common_scenic_regulons.pdf"))

unlink(str_c(path, "common_regulons.pdf"))
unlink(str_c(path, "common_scenic_regulons.pdf"))

y = plot_grid(common_scenic_regulons, common_regulons, labels = c("a", "b"), label_size = 18, ncol=1)

ggsave("paper/figures/supp_clustering_analysis_1.png",
       y,
       height = 15, width = 10)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure9.png",
       y,
       width=10, height=15)
```

#### Supp2
```{r}
tf_cor = readRDS(str_c(path, "tf_cor.rds"))

ggsave("paper/figures/supp_clustering_analysis_2.png",
       tf_cor,
       height = 5, width = 10)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure10.png",
       tf_cor,
       width=10, height=5)
```


#### Supp3
```{r "clustering analysis"}
path = "fig/clustering_analysis/"

gex_boxplot_all_hrchy = readRDS(str_c(path, "gex_boxplot_all_hrchy.rds")) +
  scale_y_continuous(breaks = c(-0.25,0,0.25,0.5))

clustering_analysis_supp_3 = plot_grid(
  gex_boxplot_all_hrchy,
  ncol = 1
  )

ggsave("paper/figures/supp_clustering_analysis_3.png", 
       clustering_analysis_supp_3,
       width = 15, height = 5)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure11.png",
       clustering_analysis_supp_3,
       width=10, height=5)

```

#### Supp4
```{r "clustering analysis"}
path = "fig/clustering_analysis/"

tf_boxplot_all_hrchy = readRDS(str_c(path, "tf_boxplot_all_hrchy.rds")) +
  scale_y_continuous(breaks = c(-0.25,0,0.25,0.5)) +
  theme(axis.text = element_text(size=12))

tf = readRDS(str_c(path, "tf_stats_plot.rds")) + theme(legend.position = "top",
                                                       legend.key.width = unit(2, "cm"))


clustering_analysis_supp_4 = plot_grid(
  tf,
  tf_boxplot_all_hrchy,
  ncol = 1, labels = c("a","b"), label_size = 18, align = "v", axis="lr"
  )

ggsave("paper/figures/supp_clustering_analysis_4.png", 
       clustering_analysis_supp_4,
       width = 12, height = 12)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure12.png",
       clustering_analysis_supp_4,
       width=12, height=12)

```


<!-- #### Supp5 -->
<!-- ```{r} -->
<!-- path = "fig/clustering_analysis/" -->
<!-- tf_lp = readRDS(str_c(path, "protocol_ranking_tf_all_hrchy.rds")) + theme(legend.position = "none") -->
<!-- pw_lp = readRDS(str_c(path, "protocol_ranking_pw_all_hrchy.rds")) + theme(legend.position = "none") -->
<!-- legend = get_legend( -->
<!--   readRDS(str_c(path, "protocol_ranking_tf_all_hrchy.rds")) + theme(legend.position = "top") -->
<!--   ) -->

<!-- x = plot_grid(legend, tf_lp, pw_lp, ncol = 1, labels = c("","a", "b"), label_size = 18, align = "v", axis = "l", rel_heights = c(0.2,1,1)) -->

<!-- ggsave("paper/figures/supp_clustering_analysis_5.png",  -->
<!--        x, -->
<!--        width = 12, height = 12) -->

<!-- ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure13.png", -->
<!--        x, -->
<!--        width=12, height=12) -->

<!-- ``` -->


#### Supp5
```{r}
path = "fig/clustering_analysis/"
pw = readRDS(str_c(path, "pw_stats_plot.rds")) + theme(legend.position = "top",
                                                       legend.key.width = unit(2, "cm"))
pw_boxplot_all_hrchy = readRDS(str_c(path, "pathway_boxplot_all_hrchy.rds")) +
  scale_y_continuous(breaks = c(-0.25,0,0.25,0.5)) +
  theme(axis.text = element_text(size=12))

clustering_analysis_supp_5 = plot_grid(
  pw, 
  pw_boxplot_all_hrchy,
  labels = c("a", "b"), label_size = 18, ncol = 1, align = "v",
  axis ="lr"
  )

ggsave("paper/figures/supp_clustering_analysis_5.png", 
       clustering_analysis_supp_5,
       width = 12, height = 12)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure13.png",
       clustering_analysis_supp_5,
       width=10, height=12)
```

#### Supp6
```{r "clustering analysis"}
path = "fig/clustering_analysis/"

scenic_hmap = readRDS(str_c(path, "scenic_hmap.rds"))
dauc_hmap = readRDS(str_c(path, "daucell_hmap.rds"))
mv_hmap = readRDS(str_c(path, "metaviper_hmap.rds"))
progeny_hmap = readRDS(str_c(path, "progeny_hmap.rds"))
pauc_hmap = readRDS(str_c(path, "paucell_hmap.rds"))



clustering_analysis_supp_6 = plot_grid(
  dauc_hmap, mv_hmap, scenic_hmap,
  progeny_hmap, pauc_hmap, rel_heights = c(1,0.6), labels = "auto", label_size = 18,
  ncol=3)

ggsave("paper/figures/supp_clustering_analysis_6.png", 
       clustering_analysis_supp_6,
       width = 15, height = 15)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure14.png",
       clustering_analysis_supp_6,
       width=15, height=15)

```

#### Supp7
```{r}
path = "fig/clustering_analysis/"
tf_vs_ess = readRDS(str_c(path, "activity_essentiality_cor.rds"))
a_plot = readRDS(str_c(path, "activity_boxplot.rds"))
e_plot = readRDS(str_c(path, "essentiality_boxplot.rds"))

ae_plot = plot_grid(a_plot, e_plot, labels = c("a", "b"), label_size = 18)

y = plot_grid(
  ae_plot,
  tf_vs_ess,
  ncol=1, labels = c("", "c"), label_size = 18
)


ggsave("paper/figures/supp_clustering_analysis_7.png",
       y,
       height = 10, width = 10)

ggsave("~/Google Drive/Paper/scRNA_benchmark/RevisionGenBio/Figures/SFigure15.png",
       y,
       width=10, height=10)
```