```{r "knitr config", cache=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::knit(..., quiet = TRUE)
```

### Libraries and sources
These libraries and sources are used in this analysis 
```{r "setup", message=F}
library(tidyverse)
library(tidylog)
library(Matrix)
library(myutils)
library(furrr)
library(ggsignif)
library(pheatmap)
library(cowplot)

options("tidylog.display" = list(print))
source("src/my_ggplot_themes.R")

#install.packages("../utils/", repos = NULL, type="source")
```
### E-ENAD-20 Minimal Residual Disease
#### Processing
```{r "load and process data"}
meta_df = read_delim(
  "data/scExpressionAtlas/E-ENAD-20/meta/E-ENAD-20.sdrf.txt", delim="\t"
  ) %>% 
  select(id = `Scan Name`, treatment = `FactorValue [compound]`, 
         day = `FactorValue [time]`, cell = `Comment [Sample_title]`) %>%
  mutate(treatment = case_when(
    treatment == "none" ~ "none",
    treatment == "dabrafenib and trametinib" ~ "MAPK_i"),
    day = as.character(day)
    )

gene_anno = read_csv("data/annotations/hgnc_ensembl_entrez.csv", col_types = "ccc") %>%
  distinct(gene = hgnc_symbol, ensembl_gene_id) %>%
  drop_na()

col_anno = read_delim(
  "data/scExpressionAtlas/E-ENAD-20/results/E-ENAD-20-quantification-filtered-files/E-ENAD-20.expression_tpm.mtx_cols"
  , delim="\t", col_names = c("j", "id")
  ) %>% 
  mutate(j = str_trim(j)) %>%
  type_convert()

row_anno = read_delim(
  "data/scExpressionAtlas/E-ENAD-20/results/E-ENAD-20-quantification-filtered-files/E-ENAD-20.expression_tpm.mtx_rows"
  , delim="\t", col_names = c("i", "ensembl_gene_id")
  ) %>% 
  mutate(i = str_trim(i)) %>%
  type_convert() %>% 
  inner_join(gene_anno, by="ensembl_gene_id")

tpm_mat = readMM(
  "data/scExpressionAtlas/E-ENAD-20/results/E-ENAD-20-quantification-filtered-files/E-ENAD-20.expression_tpm.mtx"
  ) %>% 
  summary() %>%
  as_tibble() %>%
  inner_join(col_anno, by="j") %>%
  inner_join(row_anno, by="i") %>%
  select(id, gene, expression = x) %>%
  group_by(id, gene) %>%
  summarise(expression = mean(expression)) %>%
  ungroup() %>%
  inner_join(meta_df, by="id") %>%
  mutate(day = factor(day, levels=c(0,4,28,57))) %>%
  select(cell, gene, expression, treatment, day)

tpm_mat %>%
  saveRDS("output/scExpressionAtlas/E-ENAD-20/tidy_expr.rds")

```
#### Exploratory analysis
```{r "Exploratory analysis"}
tpm_mat = readRDS("output/scExpressionAtlas/E-ENAD-20/tidy_expr.rds")

# mean expression of gene per group/day
tpm_mat %>%
  group_by(day, gene) %>%
  summarise(mean_expression = mean(expression)) %>%
  ungroup() %>%
  ggplot(aes(x=day, y=log10(mean_expression), fill=day)) +
  geom_boxplot() +
  my_theme()

tpm_mat %>%
  ggplot(aes(x=cell, y=expression)) +
  geom_boxplot()
```
#### Cluster identification
```{r "analyse cluster results"}
clusters = read_delim("data/scExpressionAtlas/E-ENAD-20/results/E-ENAD-20.clusters.tsv", delim = "\t")
marker_genes = read_delim("data/scExpressionAtlas/E-ENAD-20/results/E-ENAD-20-marker-genes-files/E-ENAD-20.marker_genes_3.tsv", delim = "\t")
tpm_mat = readRDS("output/scExpressionAtlas/E-ENAD-20/tidy_expr.rds")
# gene SGK223 not present in data
genes_of_interest = c("SLITRK6", "NGFR", "AQP1", "GFRA2", "L1CAM", "SLIT2", 
                      "BGN", "TGM2", "TNC", "CYR61", "CD36", "SLC7A8", "DLX5", 
                      "SGK223", "SLC12A7", "MLPH", "TRPM1", "GPR143", "SLC24A5",
                      "RAB27A")

m = tpm_mat %>% 
  filter(gene %in% genes_of_interest) %>%
  select(cell, gene, expression) %>%
  spread(cell, expression, fill=0) %>%
  data.frame(row.names=1)

pheatmap(m, scale = "row")
```

#### PROGENy
```{r "progeny"}
tpm_mat = readRDS("output/scExpressionAtlas/E-ENAD-20/tidy_expr.rds")

progeny_scores = run_progeny(tpm_mat, progeny_matrix_human_v1, "gene", 
                             "expression", "cell", permutation = 0) %>%
  group_by(pathway) %>%
  mutate(scaled_activity = scale(activity)) %>%
  ungroup()

## signature coverage
inner_join(tpm_mat, progeny_matrix_human_v1, by="gene") %>%
  count(cell, pathway) %>%
  group_by(pathway) %>%
  mutate(median = median(n)) %>%
  ggplot(aes(x=fct_reorder(pathway, -median), y=n)) +
  geom_boxplot() +
  coord_flip() +
  geom_hline(yintercept = 100) +
  my_theme()

# pathway score distribution
progeny_scores %>%
  ggplot(aes(x=scaled_activity)) +
  geom_density() +
  facet_wrap(~pathway, scales = "free")


# heatmap
mat = progeny_scores %>% 
  mutate(scaled_activity = case_when(scaled_activity > 6 ~ 6,
                                     TRUE ~ scaled_activity)) %>%
  select(cell, scaled_activity, pathway) %>% 
  spread(cell, scaled_activity) %>%
  data.frame(row.names=1, check.names = F)

myBreaks = c(seq(min(mat), 0, length.out=ceiling(100/2) + 1), 
              seq(max(mat)/100, max(mat), length.out=floor(100/2)))

col_annotation = progeny_scores %>% 
  distinct(cell, day, treatment) %>%
  data.frame(row.names=1)

pheatmap::pheatmap(mat, breaks=myBreaks, annotation_col = col_annotation)

# MAPK activity
progeny_scores %>%
  filter(pathway == "MAPK") %>%
  mutate(day = factor(day, levels = c(0,4,28,57))) %>%
  ggplot(aes(x=day, y=scaled_activity)) +
  geom_boxplot() +
  geom_signif(comparisons = list(c("0", "4"), c("0","28"), c("0", "57")), 
              map_signif_level=TRUE)

# EGFR activity
progeny_scores %>%
  filter(pathway == "EGFR") %>%
  mutate(day = factor(day, levels = c(0,4,28,57))) %>%
  ggplot(aes(x=day, y=scaled_activity)) +
  geom_boxplot() +
  geom_signif(comparisons = list(c("0", "4"), c("0","28"), c("0", "57")), 
              map_signif_level=TRUE)

progeny_scores %>%
  mutate(day = factor(day, levels = c(0,4,28,57))) %>%
  ggplot(aes(x=day, y=scaled_activity)) +
  geom_boxplot() + 
  facet_wrap(~pathway, scales="free") +
  geom_signif(comparisons = list(c("0", "4"), c("0","28"), c("0", "57")), 
              map_signif_level=TRUE) +
  my_theme()

```


#### DoRothEA
```{r "DoRothEA"}
cell_annotations = read_delim("data/scExpressionAtlas/E-ENAD-20/cell_phenotype_674.txt", delim = "\t")
tpm_mat = readRDS("output/scExpressionAtlas/E-ENAD-20/tidy_expr.rds") %>%
  inner_join(cell_annotations, by="cell")

# MITF expression
tpm_mat %>% 
  filter(gene == "MITF") %>%
  ggplot(aes(x=day, y=expression, color=phenotype, group = phenotype)) +
  geom_boxplot()

##### DoRothEA #####
dorothea_scores = run_viper(tpm_mat, dorothea_regulon_human_v1, "gene", "expression", "cell") %>%
  filter(confidence %in% c("A", "B"))

# signature coverage
inner_join(rename(tpm_mat, target = gene), filter(dorothea_regulon_human_v1, tf == "MITF"), by="target") %>%
  count(cell, tf) %>%
  group_by(tf) %>%
  mutate(median = median(n)) %>%
  ggplot(aes(x=fct_reorder(tf, -median), y=n)) +
  geom_boxplot() +
  geom_hline(yintercept = 35) +
  my

# tf score distribution
dorothea_scores %>%
  filter(tf == "MITF") %>%
  ggplot(aes(x=activity)) +
  geom_density()

dorothea_scores %>% 
  mutate(g = case_when(phenotype == "pigmented" ~ "pigmentend",
                       phenotype == "invasive" ~ "invasive",
                       TRUE ~ "NA")) %>%
  filter(g != "NA") %>%
  mutate(day = factor(day, levels = c(0,4,28,57))) %>%
  filter(tf == "MITF") %>%
  #filter(day == 0) %>%
  ggplot(aes(x=day, y=activity, fill = g)) +
  geom_boxplot() +
  stat_summary(aes(color=g), fun.y=mean, geom="line") +
  my_theme()

# heatmap
mat = dorothea_scores %>% 
  select(cell, activity, tf) %>% 
  spread(cell, activity) %>%
  data.frame(row.names=1, check.names = F)

myBreaks = c(seq(min(mat), 0, length.out=ceiling(100/2) + 1), 
              seq(max(mat)/100, max(mat), length.out=floor(100/2)))

col_annotation = dorothea_scores %>% 
  distinct(cell, day, treatment) %>%
  data.frame(row.names=1)

pheatmap::pheatmap(mat, breaks=myBreaks, annotation_col = col_annotation)
```